spring.application.name=BidFlow
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.data.web.pageable.serialization-mode=via_dto
jwt.secret=${JWT_SECRET}
jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS}